Psycho.io/Controllers/HeartDiseasePredictionController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Psycho.DAL.Core;
using Psycho.DAL.Core.Domain;
using Psycho.io.Mappers;
using Psycho.io.Models.HeartDiseasePrediction;
using Psycho.Logic.Models.HeartDiseasePrediction;
using Psycho.Logic.Services.Interfaces;

namespace Psycho.io.Controllers
{
    public class HeartDiseasePredictionController : Controller
    {
        private readonly IHeartDiseasePredictionService _heartDiseasePredictionService;
        private readonly UserManager<User> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly HeartDataMapper _heartDataMapper = new HeartDataMapper();
        
        public HeartDiseasePredictionController(IHeartDiseasePredictionService heartDiseasePredictionService,
            IUnitOfWork unitOfWork,
            UserManager<User> userManager)
        {
            _heartDiseasePredictionService = heartDiseasePredictionService;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Predict(HeartDataViewModel model)
        {
            var heartData = _heartDataMapper.Map(model);
            var result = _heartDiseasePredictionService.Predict(heartData);
            if (User.IsInRole("AuthorizedUser") || User.IsInRole("AnonymousUser"))
            {
                var userId = await GetCurrentUserId();
            }
            
            return Json(new { prediction = result.Prediction, probability = result.Probability, score = result.Score });
        }
        
        private async Task<int> GetCurrentUserId()
        {
            User usr = await GetCurrentUserAsync();
            return usr.Id;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
    }
}

Psycho.io/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Psycho.DAL.Core.Domain;
using Psycho.DTO.Core;
using Psycho.Logic.Facade.Interfaces;
using Psycho.DAL.Core;
using Psycho.DTO.Persistence;
using Newtonsoft.Json;
using Psycho.io.Models.User;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using System.IO;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Psycho.io.Controllers
{
    [Authorize(Roles = "Psychologist,AuthorizedUser,AnonymousUser")]
    public class UserController : PsychoMvcControllerBase
    {
        private UserManager<User> _userManager;
        private IUnitOfWork _unitOfWork;
        private IWebHostEnvironment _appEnvironment;

        public UserController(IUnitOfWork unitOfWork,
            IPsychoLogic psychoLogic,
            UserManager<User> userManager,
            IWebHostEnvironment appEnvironment) : base(psychoLogic) {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _appEnvironment = appEnvironment;
        }

        public async Task<IActionResult> ChatAsync(int? friendId = null)
        {
            List<UserChatDTO> chats = new List<UserChatDTO>();

            var user = GetCurrentUserAsync().Result;

            var listChats = await _unitOfWork.Context.Chats.Where(x => x.ReceiverId == user.Id || x.SenderId == user.Id).ToListAsync();

            var listUniq = new List<int>();
            foreach(var elem in listChats)
            {
                if(elem.SenderId != user.Id && !listUniq.Contains(elem.SenderId))
                {
                    listUniq.Add(elem.SenderId);
                }
                else if (elem.ReceiverId != user.Id && !listUniq.Contains(elem.ReceiverId))
                {
                    listUniq.Add(elem.ReceiverId);
                }
            }

            foreach(var friendsId in listUniq)
            {
                List<Chat> chat = new List<Chat>();

                foreach(var message in listChats)
                {
                    if(message.ReceiverId == friendsId || message.SenderId == friendsId)
                    {
                        chat.Add(message);
                    }
                }

                User userSender = _unitOfWork.Users.Get(friendsId);
                chats.Add(new UserChatDTO
                {
                    chat = chat,
                    User = userSender
                });
            }

            var onChatWithOpen = friendId.HasValue
                ? await _unitOfWork.Context.Psychologists.FirstOrDefaultAsync(p => p.Id == friendId.Value)
                : null;
            var chatViewModel = new ChatViewModel
            {
                OnChatWithOpen = onChatWithOpen,
                Chats = chats
            };

            return View(chatViewModel);
        }

        public async Task<IActionResult> Profile()
        {
            var user = await GetCurrentUserAsync();
            var userId = user.Id;
            UserDTO userDTO = PsychoLogic.UserFacade.GetUserDTO(userId);
            return View(userDTO);
        }

        public async Task<IActionResult> Edit(UserDTO model)
        {
            var user = await GetCurrentUserAsync();
            var userId = user.Id;
            UserDTO userDTO = PsychoLogic.UserFacade.GetUserDTO(userId);
            return View(userDTO);
        }

        public IActionResult DashboardPsychologist()
        {
            var userId = GetCurrentUserId();
            Psychologist psychologist = _unitOfWork.Psychologists.Get(userId.Result);
            var appointments = psychologist.Appointments.ToList();

            var model = new PsychologistWithAppointmentsDTO();
            model.Name = $"{psychologist.FirstName} {psychologist.LastName}";
            model.Psychologist = psychologist;
            
            List<AppointmentForCalendarDTO> list = new List<AppointmentForCalendarDTO>();
            foreach(var elem in appointments)
            {
                string sdtm = elem.StartDataTime?.Month <= 9 ? $"0{elem.StartDataTime?.Month}" : $"{elem.StartDataTime?.Month}";
                string sdtd = elem.StartDataTime?.Day <= 9 ? $"0{elem.StartDataTime?.Day}" : $"{elem.StartDataTime?.Day}";
                string sdth = elem.StartDataTime?.Hour <= 9 ? $"0{elem.StartDataTime?.Hour}" : $"{elem.StartDataTime?.Hour}";
                string sdtmin = elem.StartDataTime?.Minute <= 9 ? $"0{elem.StartDataTime?.Minute}" : $"{elem.StartDataTime?.Minute}";


                string edtm = elem.EndDataTime?.Month <= 9 ? $"0{elem.EndDataTime?.Month}" : $"{elem.EndDataTime?.Month}";
                string edtd = elem.EndDataTime?.Day <= 9 ? $"0{elem.EndDataTime?.Day}" : $"{elem.EndDataTime?.Day}";
                string edth = elem.EndDataTime?.Hour <= 9 ? $"0{elem.EndDataTime?.Hour}" : $"{elem.EndDataTime?.Hour}";
                string edtmin = elem.EndDataTime?.Minute <= 9 ? $"0{elem.EndDataTime?.Minute}" : $"{elem.EndDataTime?.Minute}";

                model.appointments.Add(new AppointmentForCalendarDTO
                {
                    id = elem.Id.ToString(),
                    title = $"{elem.AuthorizedUser.FirstName} {elem.AuthorizedUser.LastName}",
                    description = elem.AdditionalInfo,
                    start = $"{elem.StartDataTime?.Year}-{sdtm}-{sdtd}T{sdth}:{sdtmin}:00",
                    end = $"{elem.EndDataTime?.Year}-{edtm}-{edtd}T{edth}:{edtmin}:00"
                });
            }

            model.json = JsonConvert.SerializeObject(model.appointments);
            //model.appointments = list.ToArray();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CreateAppointment()
        {
            var userId = await GetCurrentUserId();
            CreateAppointmentDTO createAppointmentDTO = new CreateAppointmentDTO();
            if (User.IsInRole("Psychologist"))
            {
                createAppointmentDTO.CurrentPsychologist = _unitOfWork.Psychologists.Get(userId);
            }
            else if (User.IsInRole("AuthorizedUser"))
            {
                createAppointmentDTO.CurrentAuthorizedUser = _unitOfWork.AuthorizedUsers.Get(userId);
            }
            createAppointmentDTO.Psychologists = _unitOfWork.Psychologists.GetAll().ToList();
            createAppointmentDTO.AuthorizedUsers = _unitOfWork.AuthorizedUsers.GetAll().ToList();

            return PartialView(createAppointmentDTO);
        }

        [HttpPost]
        public IActionResult CreateAppointment(CreateAppointmentDTO model)
        {
            string _status = String.Empty;
            string _description = String.Empty;

            List<Appointment> appointments = _unitOfWork.Psychologists.Get(model.PsychologistId).Appointments.ToList();

            foreach (var elem in appointments)
            {
                if ((model.StartDateTime >= elem.StartDataTime && model.StartDateTime <= elem.EndDataTime) ||
                    (model.EndDateTime >= elem.StartDataTime && model.EndDateTime <= elem.EndDataTime) ||
                    (elem.StartDataTime >= model.StartDateTime && elem.EndDataTime <= model.EndDateTime))
                {
                    _status = "error";
                    _description = "Doctor is busy at that time.";
                    break;
                }
            }

            if (_status != "error")
            {
                Appointment appointment = new Appointment
                {
                    PsychologistId = model.PsychologistId,
                    AuthorizedUserId = model.AuthorizedUserId,
                    StartDataTime = model.StartDateTime,
                    EndDataTime = model.EndDateTime,
                    AdditionalInfo = model.Info,
                    Finished = false
                };

                _unitOfWork.Appointments.Add(appointment);
                int result = _unitOfWork.Complete();

                _status = "success";
                _description = "Appointment created.";
            }
            //if (User.IsInRole("Doctor"))
            {
                //return RedirectToAction("DashboardDoctor", "User", new { showAll = false });
            }
            //else
            {
                //return RedirectToAction("DashboardPatient", "User", new { showAll = false });
            }

            return Json(new { status = _status, description = _description });
        }

        public IActionResult DashboardAuthorizedUser()
        {
            var userId = GetCurrentUserId();
            AuthorizedUser user = _unitOfWork.AuthorizedUsers.Get(userId.Result);
            var appointments = user.Appointments.ToList();

            var model = new AuthorizedUserWithAppointmentsDTO();
            model.Name = $"{user.FirstName} {user.LastName}";
            model.AuthorizedUser = user;
            
            List<AppointmentForCalendarDTO> list = new List<AppointmentForCalendarDTO>();
            foreach (var elem in appointments)
            {
                string sdtm = elem.StartDataTime?.Month <= 9 ? $"0{elem.StartDataTime?.Month}" : $"{elem.StartDataTime?.Month}";
                string sdtd = elem.StartDataTime?.Day <= 9 ? $"0{elem.StartDataTime?.Day}" : $"{elem.StartDataTime?.Day}";
                string sdth = elem.StartDataTime?.Hour <= 9 ? $"0{elem.StartDataTime?.Hour}" : $"{elem.StartDataTime?.Hour}";
                string sdtmin = elem.StartDataTime?.Minute <= 9 ? $"0{elem.StartDataTime?.Minute}" : $"{elem.StartDataTime?.Minute}";


                string edtm = elem.EndDataTime?.Month <= 9 ? $"0{elem.EndDataTime?.Month}" : $"{elem.EndDataTime?.Month}";

Psycho.io/Views/Shared/_AdminPageLayout.cshtml

@{
    var content = ((HospitalContent)ViewData["lang"])?.Layout;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"] - Psycho.io</title>

    @Html.Partial("_Favicons")

    <link href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" rel="stylesheet">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/mdb.min.css" rel="stylesheet">

    <!--Sign in modal-->
    <link href="~/css/signin.css" rel="stylesheet">
    <link href="~/css/toastr.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    @RenderSection("csss", required: false)

</head>
<body class="medical-lp" style="height: auto;">

    <!--Navigation & Intro-->
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="background-color: rgba(0, 0, 0, 0.2);">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="../img/psycho.png"/></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!--Links-->
                <ul class="navbar-nav mr-auto smooth-scroll">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">@(content?.Home ?? "Home") <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about" data-offset="100">@(content?.AboutNav ?? "About")</a>
                    </li>
                    <!--<li class="nav-item">
                        <a class="nav-link" href="#services" data-offset="100">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#features" data-offset="100">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#testimonials" data-offset="100">Testimonials</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#modal-info">Info</a>
                    </li>-->
                </ul>

                <!--Social Icons-->
                <ul class="navbar-nav ">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Profile" asp-controller="User">@User.Identity.Name</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a asp-controller="Admin" asp-action="Index" class="nav-link"><i class="fas fa-users-cog"></i></a>
                            </li>
                        }
                        <li class="nav-item">
                            <a id="sign-out" class="nav-link"><i class="fas fa-sign-out-alt"></i></a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a id="sign-in" class="nav-link">@(content?.SignIn ?? "Sign in")</a>
                        </li>
                        <li class="nav-item">
                            <a id="sign-up" asp-controller="Account" asp-action="Signup" class="nav-link">@(content?.SignUp ?? "Sign up")</a>
                        </li>
                    }
                    
                    @{
                        string selectedLang = Context.Request.Cookies.ContainsKey("lang") ? Context.Request.Cookies["lang"] : "en";
                    }
                    
                    <li class="nav-item" style="display: flex !important; margin-top: auto !important; margin-bottom: auto !important; padding: 0 0 0 8px !important;">
                        <select class="nav-item" style="display: inline-block !important;" name="lang" id="change-lang">
                            @if (selectedLang == "ua")
                            {
                                <option value="en">🇬🇧</option>
                                <option value="ua" selected>🇺🇦</option>
                            }
                            else if (selectedLang == "en")
                            {
                                <option value="en" selected>🇬🇧</option>
                                <option value="ua">🇺🇦</option>
                            }
                        </select>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!--/Navbar-->


    @RenderBody()

    <script type="text/javascript" src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="~/js/popper.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="~/js/mdb.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    <script type="text/javascript" src="~/js/sign-in.js"></script>
    <script type="text/javascript" src="~/js/sign-up.js"></script>
    <script type="text/javascript" src="~/js/sign-out.js"></script>
    <script type="text/javascript" src="~/js/toastr.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">        
        $('#change-lang').on('change', function() {
            $.cookie("lang", this.value, { path: '/' });
            document.location.reload();
        });
    </script>

    @RenderSection("scripts", required: false)

</body>
</html>

Psycho.io/Views/Shared/_Favicons.cshtml

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

Psycho.io/Views/Shared/_Layout.cshtml

@{
    var content = ((HospitalContent)ViewData["lang"])?.Layout;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"] - Hospital.io</title>

    @Html.Partial("_Favicons")

    <link href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" rel="stylesheet">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/mdb.min.css" rel="stylesheet">
    <link href="~/css/layout.css" rel="stylesheet">
    <link href="~/css/toastr.min.css" rel="stylesheet">
    <link href="~/css/fullcalendar.css" rel="stylesheet">

    <!--Sign in modal-->
    <link href="~/css/signin.css" rel="stylesheet">
    <!--<link href="https://mdbootstrap.com/wp-content/themes/mdbootstrap4/css/compiled-4.7.7.min.css?ver=4.7.7" rel="stylesheet">-->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    <style>
        a .dropdown-item:hover {
          /*background-color: ;*/
        }
    </style>


    @RenderSection("csss", required: false)

</head>
<body class="medical-lp">

    <!--Navigation & Intro-->
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="background-color: rgba(0, 0, 0, 0.2);">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/img/psycho.png" s /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!--Links-->
                <ul class="navbar-nav mr-auto smooth-scroll">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">@(content?.Home ?? "Home") <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Psychologist" asp-action="Index">@(content?.DoctorsNav ?? "Doctors")</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarToolsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          @(content?.ToolsNav ?? "Tools")
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarToolsDropdown">
                            <a class="dropdown-item" asp-controller="HeartDiseasePrediction" asp-action="Index">@(content?.HeartDiseasePredictionNav ?? "Heart Disease Prediction")</a>
                            @*<div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>*@
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about" data-offset="100">@(content?.AboutNav ?? "About")</a>
                    </li>
                    <!--<li class="nav-item">
                        <a class="nav-link" href="#services" data-offset="100">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#features" data-offset="100">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#testimonials" data-offset="100">Testimonials</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#modal-info">Info</a>
                    </li>-->
                </ul>

                <!--Social Icons-->
                <ul class="navbar-nav ">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Admin" asp-action="Index" class="nav-link"><i class="fas fa-users-cog"></i></a>
                            </li>
                        }
                        @if (User.IsInRole("Psychologist"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Profile" asp-controller="User">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="User" asp-action="Chat" class="nav-link"><i class="fas fa-envelope"></i></a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="User" asp-action="DashboardPsychologist" class="nav-link"><i class="far fa-calendar-alt"></i></a>
                            </li>
                        }
                        else if (User.IsInRole("AuthorizedUser"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Profile" asp-controller="User">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="User" asp-action="Chat" class="nav-link"><i class="fas fa-envelope"></i></a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="User" asp-action="DashboardAuthorizedUser" class="nav-link"><i class="far fa-calendar-alt"></i></a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Diary" asp-action="HealthDiary" class="nav-link"><i class="fas fa-book-medical"></i></a>
                            </li>
                        }
                        else if (User.IsInRole("AnonymousUser"))
                        {
                            <li class="nav-item">
                                <a class="nav-link">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="User" asp-action="Chat" class="nav-link"><i class="fas fa-envelope"></i></a>
                            </li>
                        }
                        <li class="nav-item">
                            <a id="sign-out" class="nav-link"><i class="fas fa-sign-out-alt"></i></a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a id="sign-in" class="nav-link">@(content?.SignIn ?? "Sign in")</a>
                        </li>
                        <li class="nav-item">
                            <a id="sign-up" asp-controller="Account" asp-action="Signup" class="nav-link">@(content?.SignUp ?? "Sign up")</a>
                        </li>
                    }
                    
                    @{
                        string selectedLang = Context.Request.Cookies.ContainsKey("lang") ? Context.Request.Cookies["lang"] : "en";
                    }
                    
                    <li class="nav-item" style="display: flex !important; margin-top: auto !important; margin-bottom: auto !important; padding: 0 0 0 8px !important;">
                        <select class="nav-item" style="display: inline-block !important;" name="lang" id="change-lang">
                            @if (selectedLang == "ua")
                            {
                                <option value="en">🇬🇧</option>
                                <option value="ua" selected>🇺🇦</option>
                            }
                            else if (selectedLang == "en")
                            {
                                <option value="en" selected>🇬🇧</option>
                                <option value="ua">🇺🇦</option>
                            }
                        </select>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
    <!--/Navbar-->

    <div class="modal fade" id="elegantModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div id="dialogContent" class="modal-dialog" role="document"></div>
    </div>

    <div class="modal fade" id="darkModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div id="dialogContentUp" class="modal-dialog form-dark" role="document"></div>
    </div>

    @RenderBody()

    <script type="text/javascript" src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="~/js/popper.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="~/js/mdb.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    <script type="text/javascript" src="~/js/sign-in.js"></script>
    <script type="text/javascript" src="~/js/sign-up.js"></script>
    <script type="text/javascript" src="~/js/sign-out.js"></script>
    <script type="text/javascript" src="~/js/toastr.min.js"></script>
    <script type="text/javascript" src="~/js/moment-with-locales.js"></script>
    <script type="text/javascript" src="~/js/fullcalendar.js"></script>
    <script type="text/javascript" src="~/js/jquery.unobtrusive-ajax.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>

    <script type="text/javascript">
        $.fn.datetimepicker.Constructor.Default = $.extend({}, $.fn.datetimepicker.Constructor.Default, {
            icons: {
                time: 'fas fa-clock',
                date: 'fas fa-calendar',
                up: 'fas fa-arrow-up',
                down: 'fas fa-arrow-down',
                previous: 'fas fa-chevron-left',
                next: 'fas fa-chevron-right',
                today: 'fas fa-calendar-check-o',
                clear: 'fas fa-trash',
                close: 'fas fa-times'
            }
        });
        
        $('#change-lang').on('change', function() {
            $.cookie("lang", this.value, { path: '/' });
            document.location.reload();
        });
    </script>

    @RenderSection("scripts", required: false)

</body>
</html>