Psycho.io/Models/Diary/DiaryViewModel.cs
using System.Collections.Generic;
using Psycho.DAL.Core.Domain;

namespace Psycho.io.Models.Diary
{
    public class DiaryViewModel
    {
        public List<MoodIdentification> DefaultMoods { get; set; }
        public List<SymptomIdentification> DefaultSymptoms { get; set; }
        public List<LifestyleIdentification> DefaultLifestyles { get; set; }

        public List<string> UserMoods { get; set; }
        public List<string> UserSymptoms { get; set; }
        public List<string> UserLifestyles { get; set; }

        public List<BodyIndicator> UserBodyIndicators { get; set; }
    }
}

Psycho.io/Models/Diary/GraphDataViewModel.cs
using System.Collections.Generic;

namespace Psycho.io.Models.Diary
{
    public class GraphDataViewModel
    {
        public List<decimal> SeriesData { get; set; }
        public List<string> XaxisCategories { get; set; }
    }
}

Psycho.io/Models/Diary/LifestyleIdentification.cs
namespace Psycho.io.Models.Diary
{
    public class LifestyleIdentification
    {
        public string LifestyleId { get; set; }
        public string LifestyleDescription { get; set; }
        public bool Popover { get; set; }
    }
}

Psycho.io/Models/Diary/MoodIdentification.cs
namespace Psycho.io.Models.Diary
{
    public class MoodIdentification
    {
        public string MoodId { get; set; }
        public string MoodDescription { get; set; }
    }
}

Psycho.io/Models/Diary/StatisticsViewModel.cs
namespace Psycho.io.Models.Diary
{
    public class StatisticsViewModel
    {
        public GraphDataViewModel WaterGraph { get; set; }
        public GraphDataViewModel WeightGraph { get; set; }
        public GraphDataViewModel SleepGraph { get; set; }
        public GraphDataViewModel TemperatureGraph { get; set; }
    }
}

Psycho.io/Models/Diary/SymptomIdentification.cs
namespace Psycho.io.Models.Diary
{
    public class SymptomIdentification
    {
        public string SymptomId { get; set; }
        public string SymptomDescription { get; set; }
    }
}

Psycho.io/Controllers/DiaryController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Psycho.DAL.Core;
using Psycho.DAL.Core.Domain;
using Psycho.io.Models.Diary;
using Psycho.Logic.Facade.Interfaces;


namespace Psycho.io.Controllers
{
    [Authorize(Roles = "AuthorizedUser")]
    public class DiaryController : PsychoMvcControllerBase
    {
        private UserManager<User> _userManager;
        private IUnitOfWork _unitOfWork;

        public DiaryController(IUnitOfWork unitOfWork,
            IPsychoLogic psychoLogic,
            UserManager<User> userManager) : base(psychoLogic)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult HealthDiary()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Diary()
        {
            var userId = await GetCurrentUserId();
            var day = DateTime.Today;

            var diary = await _unitOfWork.Context.HealthDiary.Where(r => r.UserId == userId && r.Date == day).ToListAsync();
            var bodyIndicators = await _unitOfWork.Context.BodyIndicators.Where(r => r.UserId == userId && r.Date == day).ToListAsync();

            var userMoods = diary.Where(r => r.BlockName == "mood").Select(r => r.BlockValue).ToList();
            var userSymptoms = diary.Where(r => r.BlockName == "symptom").Select(r => r.BlockValue).ToList();
            var userLifestyles = diary.Where(r => r.BlockName == "lifestyle").Select(r => r.BlockValue).ToList();

            var viewModel = new DiaryViewModel
            {
                DefaultMoods = Constants.Constants.Diary.Moods,
                DefaultSymptoms = Constants.Constants.Diary.Symptoms,
                DefaultLifestyles = Constants.Constants.Diary.Lifestyles,

                UserMoods = userMoods,
                UserSymptoms = userSymptoms,
                UserLifestyles = userLifestyles,

                UserBodyIndicators = bodyIndicators
            };

            return PartialView(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Statistics()
        {
            var userId = await GetCurrentUserId();
            var end = DateTime.Today;
            var start = end.AddDays(-6);

            var bodyIndicators = await _unitOfWork.Context.BodyIndicators
                .Where(r => r.UserId == userId && r.Date >= start.Date && r.Date <= end.Date)
                .ToListAsync();

            var water = bodyIndicators.Where(i => i.Indicator == "drink-water");
            var waterSeriesData = new List<decimal>();
            var waterXaxisCategories = new List<string>();
            var weight = bodyIndicators.Where(i => i.Indicator == "weight");
            var weightSeriesData = new List<decimal>();
            var weightXaxisCategories = new List<string>();
            var sleep = bodyIndicators.Where(i => i.Indicator == "sleep");
            var sleepSeriesData = new List<decimal>();
            var sleepXaxisCategories = new List<string>();
            var temperature = bodyIndicators.Where(i => i.Indicator == "temperature");
            var temperatureSeriesData = new List<decimal>();
            var temperatureXaxisCategories = new List<string>();
            foreach (DateTime day in EachDay(start, end))
            {
                var waterElem = water.FirstOrDefault(w => w.Date.Date == day.Date);
                waterSeriesData.Add(waterElem?.Value ?? 0m);
                waterXaxisCategories.Add(day.Date.ToString("d", CultureInfo.CreateSpecificCulture("en-US")));

                var weightElem = weight.FirstOrDefault(w => w.Date.Date == day.Date);
                weightSeriesData.Add(weightElem?.Value ?? 0m);
                weightXaxisCategories.Add(day.Date.ToString("d", CultureInfo.CreateSpecificCulture("en-US")));

                var sleepElem = sleep.FirstOrDefault(w => w.Date.Date == day.Date);
                sleepSeriesData.Add(sleepElem?.Value ?? 0m);
                sleepXaxisCategories.Add(day.Date.ToString("d", CultureInfo.CreateSpecificCulture("en-US")));

                var temperatureElem = temperature.FirstOrDefault(w => w.Date.Date == day.Date);
                temperatureSeriesData.Add(temperatureElem?.Value ?? 0m);
                temperatureXaxisCategories.Add(day.Date.ToString("d", CultureInfo.CreateSpecificCulture("en-US")));
            }

            var viewModel = new StatisticsViewModel
            {
                WaterGraph = new GraphDataViewModel { SeriesData = waterSeriesData, XaxisCategories = waterXaxisCategories },
                WeightGraph = new GraphDataViewModel { SeriesData = weightSeriesData, XaxisCategories = weightXaxisCategories },
                SleepGraph = new GraphDataViewModel { SeriesData = sleepSeriesData, XaxisCategories = sleepXaxisCategories },
                TemperatureGraph = new GraphDataViewModel { SeriesData = temperatureSeriesData, XaxisCategories = temperatureXaxisCategories }
            };

            return PartialView(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddDiaryRecord(string value, string blockName, DateTime date)
        {
            var record = new HealthDiary
            {
                UserId = await GetCurrentUserId(),
                Date = date.Date,
                BlockName = blockName,
                BlockValue = value
            };

            _unitOfWork.Context.HealthDiary.Add(record);
            await _unitOfWork.Context.SaveChangesAsync();

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> RemoveDiaryRecord(string value, string blockName, DateTime date)
        {
            var userId = await GetCurrentUserId();
            var day = date.Date;
            var record = await _unitOfWork.Context.HealthDiary.FirstOrDefaultAsync(r =>
                r.UserId == userId
                && r.BlockName == blockName
                && r.BlockValue == value
                && r.Date == day);

            if(record != null)
            {
                _unitOfWork.Context.HealthDiary.Remove(record);
                await _unitOfWork.Context.SaveChangesAsync();
            }

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdateBodyIndicator(decimal value, string indicator, DateTime date)
        {
            var userId = await GetCurrentUserId();
            var day = date.Date;
            var record = await _unitOfWork.Context.BodyIndicators.FirstOrDefaultAsync(r =>
                r.UserId == userId
                && r.Indicator == indicator
                && r.Date == day);

            if(record != null)
            {
                record.Value = value;
            }
            else
            {
                var newRecord = new BodyIndicator
                {
                    UserId = userId,
                    Date = day,
                    Indicator = indicator,
                    Value = value
                };

                _unitOfWork.Context.BodyIndicators.Add(newRecord);
            }

            await _unitOfWork.Context.SaveChangesAsync();

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> RemoveBodyIndicator(string indicator, DateTime date)
        {
            var userId = await GetCurrentUserId();
            var day = date.Date;
            var record = await _unitOfWork.Context.BodyIndicators.FirstOrDefaultAsync(r =>
                r.UserId == userId
                && r.Indicator == indicator
                && r.Date == day);

            if (record != null)
            {
                _unitOfWork.Context.BodyIndicators.Remove(record);
                await _unitOfWork.Context.SaveChangesAsync();
            }

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> ChangeDiaryDay(DateTime date)
        {
            var userId = await GetCurrentUserId();
            var day = date.Date;

            var diary = await _unitOfWork.Context.HealthDiary.Where(r => r.UserId == userId && r.Date == day).ToListAsync();
            var bodyIndicators = await _unitOfWork.Context.BodyIndicators.Where(r => r.UserId == userId && r.Date == day).ToListAsync();

            var userMoods = diary.Where(r => r.BlockName == "mood").Select(r => r.BlockValue).ToList();
            var userSymptoms = diary.Where(r => r.BlockName == "symptom").Select(r => r.BlockValue).ToList();
            var userLifestyles = diary.Where(r => r.BlockName == "lifestyle").Select(r => r.BlockValue).ToList();

            return new OkObjectResult(new
            {
                userMoods = userMoods,
                userSymptoms = userSymptoms,
                userLifestyles = userLifestyles,
                bodyIndicators = bodyIndicators
            });
        }

        public async Task<IActionResult> ChangeWaterGraphRange(DateTime start, DateTime end)
        {
            var userId = await GetCurrentUserId();
            start = start.Date;
            end = end.Date;

            var bodyIndicators = await _unitOfWork.Context.BodyIndicators
                .Where(r => r.UserId == userId && r.Date >= start.Date && r.Date <= end.Date)
                .ToListAsync();

            var water = bodyIndicators.Where(i => i.Indicator == "drink-water");
            var waterSeriesData = new List<decimal>();
            var waterXaxisCategories = new List<string>();
            foreach (DateTime day in EachDay(start, end))
            {
                var waterElem = water.FirstOrDefault(w => w.Date.Date == day.Date);
                waterSeriesData.Add(waterElem?.Value ?? 0m);

Psycho.io/Views/Diary/Diary.cshtml
@model Psycho.io.Models.Diary.DiaryViewModel

@{
    var content = ((HospitalContent)ViewData["lang"])?.Diary?.HealthDiary;
}

<link href="~/css/diary/diary.css" rel="stylesheet">

<div id="diaryUtils"
     class="display-none"
     add-diary-record-url="@Url.Action("AddDiaryRecord", "Diary")"
     remove-diary-record-url="@Url.Action("RemoveDiaryRecord", "Diary")"
     add-or-update-body-indicator-url="@Url.Action("AddOrUpdateBodyIndicator", "Diary")"
     remove-body-indicator-url="@Url.Action("RemoveBodyIndicator", "Diary")"
     change-diary-day-url="@Url.Action("ChangeDiaryDay", "Diary")">
</div>

<div class="row text-center">
    <div class="col-md-9 mb-4">
        <div class="card card-cascade cascading-admin-card user-card">
            <div class="admin-up d-flex justify-content-start">
                <i class="fas fa-running light-green py-4 mr-3 z-depth-2"></i>
                <div class="data">
                    <h5 class="font-weight-bold dark-grey-text">
                        @(content?.Lifestyle ?? "Lifestyle")
                    </h5>
                </div>
            </div>
            <div class="card-body card-body-cascade">
                <div id="lifestyle-container" class="col-md-12 mb-5 d-flex flex-wrap justify-content-between">
                    @foreach (var defaultLifestyle in Model.DefaultLifestyles)
                    {
                        @if (defaultLifestyle.Popover)
                        {
                            var unit = defaultLifestyle.LifestyleId == "drink-water"
                                ? "L"
                                : defaultLifestyle.LifestyleId == "weight"
                                    ? "kg"
                                    : defaultLifestyle.LifestyleId == "sleep"
                                        ? "h"
                                        : "°C";
                            var selectedLifestyle = "";
                            var inputedValue = 0m;
                            var record = Model.UserBodyIndicators.FirstOrDefault(r => r.Indicator == defaultLifestyle.LifestyleId);
                            if (record != null)
                            {
                                selectedLifestyle = "selected-lifestyle";
                                inputedValue = record.Value;
                            }
                            <div data-toggle="tooltip" title="@defaultLifestyle.LifestyleDescription" class="m-4">
                                <a data-toggle="modal" data-target="#@string.Format("{0}-modal", defaultLifestyle.LifestyleId)">
                                    <img id="@defaultLifestyle.LifestyleId" src="@string.Format("../img/diary/lifestyle/lifestyle-{0}.png", defaultLifestyle.LifestyleId)" class="md-avatar rounded-circle size-2 @selectedLifestyle" alt="image">
                                </a>
                            </div>

                            <div class="modal fade" id="@string.Format("{0}-modal", defaultLifestyle.LifestyleId)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title w-100">@defaultLifestyle.LifestyleDescription</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="input-group mb-3">
                                                <input id="@string.Format("{0}-input", defaultLifestyle.LifestyleId)" class="form-control lifestyle-input" type="number" value="@inputedValue" placeholder="" aria-label="" aria-describedby="@string.Format("{0}-addon", defaultLifestyle.LifestyleId)">
                                                <div class="input-group-append">
                                                    <span class="input-group-text" id="@string.Format("{0}-addon", defaultLifestyle.LifestyleId)">@unit</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-light btn-sm" data-dismiss="modal">Close</button>
                                            <button type="button" class="btn btn-primary btn-sm" onclick="savePopupClick('@defaultLifestyle.LifestyleId')">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            var selectedLifestyle = Model.UserLifestyles.Contains(defaultLifestyle.LifestyleId) ? "selected-lifestyle" : "";
                            <div data-toggle="tooltip" title="@defaultLifestyle.LifestyleDescription" class="m-4 simple-lifestyle-pick">
                                <a>
                                    <img id="@defaultLifestyle.LifestyleId" src="@string.Format("../img/diary/lifestyle/lifestyle-{0}.png", defaultLifestyle.LifestyleId)" class="md-avatar rounded-circle size-2 @selectedLifestyle" alt="image">
                                </a>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>

        <div class="card card-cascade cascading-admin-card user-card">
            <div class="admin-up d-flex justify-content-start">
                <i class="fas fa-thermometer-half light-blue lighten-2 py-4 mr-3 z-depth-2"></i>
                <div class="data">
                    <h5 class="font-weight-bold dark-grey-text">
                        @(content?.Symptoms ?? "Symptoms")
                    </h5>
                </div>
            </div>
            <div class="card-body card-body-cascade">
                <div id="symptoms-container" class="col-md-12 mb-5 d-flex flex-wrap justify-content-between">
                    @foreach (var defaultSymptom in Model.DefaultSymptoms)
                    {
                        var selectedSymptom = @Model.UserSymptoms.Contains(defaultSymptom.SymptomId) ? "selected-symptom" : "";
                        <div data-toggle="tooltip" title="@defaultSymptom.SymptomDescription" class="m-4">
                            <a>
                                <img id="@defaultSymptom.SymptomId" src="@string.Format("../img/diary/symptoms/symptom-{0}.png", defaultSymptom.SymptomId)" class="md-avatar rounded-circle size-2 @selectedSymptom" alt="image">
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>

        <div class="card card-cascade cascading-admin-card user-card">
            <div class="admin-up d-flex justify-content-start">
                <i class="far fa-laugh-wink amber lighten-1 py-4 mr-3 z-depth-2"></i>
                <div class="data">
                    <h5 class="font-weight-bold dark-grey-text">
                        @(content?.Mood ?? "Mood")
                    </h5>
                </div>
            </div>
            <div class="card-body card-body-cascade">
                <div id="mood-container" class="col-md-12 mb-5 d-flex flex-wrap justify-content-between">
                    @foreach(var defaultMood in Model.DefaultMoods)
                    {
                        var selectedMood = Model.UserMoods.Contains(defaultMood.MoodId) ? "selected-mood" : "";
                        <div data-toggle="tooltip" title="@defaultMood.MoodDescription" class="m-4">
                            <a>
                                <img id="@defaultMood.MoodId" src="@string.Format("../img/diary/mood/mood-{0}.png", defaultMood.MoodId)" class="md-avatar rounded-circle size-2 @selectedMood" alt="image">
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3 mb-4">
        <div style="margin-top: 100px;">
            <div class="/*col-md-10 offset-md-1*/">
                <div id="miniCalendar" data-language='en' class=""></div>
            </div>
        </div>
    </div>
</div>

<script>
    var globalCurrentDate = new Date();

    $('#miniCalendar').datepicker({
        inline: true,
        todayButton: new Date(),
        maxDate: new Date(),
        onSelect: function (formattedDate, date, inst) {
            globalCurrentDate = date;
            changeDiaryDay(date);
        }
    });

    $('[data-toggle="tooltip"]').tooltip()

    $(document).on("click", "#lifestyle-container .simple-lifestyle-pick img", function () {
        if ($(this).hasClass("selected-lifestyle")) {
            $(this).removeClass("selected-lifestyle");
            removeDiaryRecord($(this).attr('id'), 'lifestyle', globalCurrentDate);
        } else {
            $(this).addClass("selected-lifestyle");
            addDiaryRecord($(this).attr('id'), 'lifestyle', globalCurrentDate);
        }
    });

    $(document).on("click", "#symptoms-container img", function () {
        if ($(this).hasClass("selected-symptom")) {
            $(this).removeClass("selected-symptom");
            removeDiaryRecord($(this).attr('id'), 'symptom', globalCurrentDate);
        } else {
            $(this).addClass("selected-symptom");
            addDiaryRecord($(this).attr('id'), 'symptom', globalCurrentDate);
        }
    });

    $(document).on("click", "#mood-container img", function () {
        if ($(this).hasClass("selected-mood")) {
            $(this).removeClass("selected-mood");
            removeDiaryRecord($(this).attr('id'), 'mood', globalCurrentDate);
        } else {
            $(this).addClass("selected-mood");
            addDiaryRecord($(this).attr('id'), 'mood', globalCurrentDate);
        }
    });

    function savePopupClick(lifeStyleId) {
        var input = $(`#${lifeStyleId}-input`).val();
        if (input) {
            $(`#${lifeStyleId}`).addClass("selected-lifestyle");
            addOrUplateBodyIndicator(input, lifeStyleId, globalCurrentDate);
        } else {
            $(`#${lifeStyleId}`).removeClass("selected-lifestyle");
            removeBodyIndicator(lifeStyleId, globalCurrentDate);
        }
        $(`#${lifeStyleId}-modal`).modal('hide');
    }

    function addDiaryRecord(value, blockName, date) {
        $.ajax({
            url: $("#diaryUtils").attr("add-diary-record-url"),
            method: "POST",
            data: {value: value,blockName: blockName,date: date.toDateString()
            }
        });
    }

    function removeDiaryRecord(value, blockName, date) {
        $.ajax({
            url: $("#diaryUtils").attr("remove-diary-record-url"),
            method: "POST",
            data: {value: value,blockName: blockName,date: date.toDateString()}
        });
    }

    function addOrUplateBodyIndicator(value, indicator, date) {
        $.ajax({
            url: $("#diaryUtils").attr("add-or-update-body-indicator-url"),
            method: "POST",
            data: { value: value, indicator: indicator, date: date.toDateString() }
        });
    }

    function removeBodyIndicator(indicator, date) {
        $.ajax({
            url: $("#diaryUtils").attr("remove-body-indicator-url"),
            method: "POST",
            data: { indicator: indicator, date: date.toDateString() }
        });
    }

    function changeDiaryDay(date) {
        $.ajax({
            url: $("#diaryUtils").attr("change-diary-day-url"),
            method: "POST",
            data: { date: date.toDateString() },
            success: function (data) {
                $("#lifestyle-container img").removeClass("selected-lifestyle");
                $(".lifestyle-input").val(0);
                $("#symptoms-container img").removeClass("selected-symptom");
                $("#mood-container img").removeClass("selected-mood");

                $.each(data.userLifestyles, (index, value) => $(`#${value}`).addClass("selected-lifestyle"));
                $.each(data.bodyIndicators, (index, obj) => {
                    $(`#${obj.indicator}-input`).val(obj.value);
                    $(`#${obj.indicator}`).addClass("selected-lifestyle")
                });
                $.each(data.userSymptoms, (index, value) => $(`#${value}`).addClass("selected-symptom"));
                $.each(data.userMoods, (index, value) => $(`#${value}`).addClass("selected-mood"));
            }
        });
    }
</script>

Psycho.io/Views/Diary/HealthDiary.cshtml
@{
    ViewData["Title"] = "Health Diary";
    var content = ((HospitalContent)ViewData["lang"])?.Diary?.Nav;
}

@section csss{
    <link href="~/css/profile.css" rel="stylesheet">
    <link href="~/css/utils/datepicker.css" rel="stylesheet" type="text/css">
    <style>
        .dislay-none {
            display: none;
        }
    </style>
}

<div id="healthDiaryUtils"
     class="display-none"
     show-app-info-url="@Url.Action("ShowAppointmentResultForPatientInfo", "User")"
     download-analysis-url="@Url.Action("DownloadAnalysis", "User")">
</div>

<div class="modal fade" id="createAppModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="createAppDialog" class="modal-dialog modal-lg" role="document"></div>
</div>
<div class="modal fade" id="showAppResult" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="showAppDialog" class="modal-dialog modal-lg" role="document" style="max-width: 1100px;"></div>
</div>

<main>
    <div class="container-fluid">
        <section class="section team-section">
            <div class="row">
                <div class="col-md-12">
                    <ul class="nav md-tabs nav-justified">
                        <li class="nav-item waves-effect waves-light">
                            <a class="nav-link active nav-btn" data-toggle="tab" href="#Diary" role="tab"
                               data-url="@Url.Action("Diary", "Diary")"
                               data-content-id="Diary"
                               id="healthDiaryNav">@(content?.HealthDiary ?? "Health Diary")</a>
                        </li>
                        <li class="nav-item waves-effect waves-light">
                            <a class="nav-link nav-btn" data-toggle="tab" href="#Statistics" role="tab"
                               data-url="@Url.Action("Statistics", "Diary")"
                               data-content-id="Statistics"
                               id="statisticsNav">@(content?.Statistics ?? "Statistics")</a>
                        </li>
                    </ul>

                    <div class="tab-content card">
                        <div id="Diary" class="tab-pane fade show active tab-with-content"></div>
                        <div id="Statistics" class="tab-pane fade tab-with-content"></div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</main>

@section scripts{
    <script type="text/javascript" src="~/js/utils/datepicker.js"></script>
    <script type="text/javascript" src="~/js/utils/datepicker.en.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script>
        function loadPage(tabSelector, url) {
            var content = $(tabSelector).html();
            if (content && tabSelector !== '#Statistics') {
                return;
            }

            $.ajax({
                url: url,
                method: "GET",
                success: function (res) {
                    $(tabSelector).html(res);
                }
            });
        }

        $(".nav-btn").click(function (elem) {
            var elemSelector = "#" + $(elem.currentTarget).attr('data-content-id');;
            var dataUrl = $(elem.currentTarget).attr('data-url');
            loadPage(elemSelector, dataUrl);
        });

        var initContentSelector = "#" + $("#healthDiaryNav").attr("data-content-id");
        var initUrl = $("#healthDiaryNav").attr("data-url");
        loadPage(initContentSelector, initUrl);
        
    </script>
}