Psycho.io/Controllers/PsychologistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Psycho.DAL.Core;
using Psycho.DAL.Core.Domain;
using Psycho.DTO.Core;
using Psycho.DTO.Persistence;
using Psycho.io.Models.Doctor;
using Psycho.Logic.Facade.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Psycho.io.Controllers
{
    [Authorize]
    public class PsychologistController : PsychoMvcControllerBase
    {
        private readonly UserManager<User> _userManager;
        private IUnitOfWork _unitOfWork;

        public PsychologistController(IUnitOfWork unitOfWork, IPsychoLogic psychoLogic,
            UserManager<User> userManager)
            : base(psychoLogic)
        {
            this._unitOfWork = unitOfWork;
            this._userManager = userManager;
        }

        // GET: /<controller>/
        [AllowAnonymous]
        public IActionResult Index()
        {
            PsychologistListDTO psychologistListDTO = PsychoLogic.AdminFacade.GetPsychologistListForAdminPage();
            var doctors = new PsychologistListDTO
            {
                PsychologistDTOs = psychologistListDTO.PsychologistDTOs//.Take(10).ToList()
            };

            var viewModel = new DoctorsViewModel
            {
                Doctors = doctors,
                NumberOfPages = (int)Math.Ceiling((double)doctors.PsychologistDTOs.Count / 10)
            };

            return View(viewModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Schedule(int id)
        {
            Psychologist psychologist = _unitOfWork.Psychologists.Get(id);
            var appointments = psychologist.Appointments.ToList();

            var model = new PsychologistWithAppointmentsDTO();
            model.Name = $"{psychologist.FirstName} {psychologist.LastName}";
            model.Psychologist = psychologist;

            List<AppointmentForCalendarDTO> list = new List<AppointmentForCalendarDTO>();
            foreach (var elem in appointments)
            {
                string sdtm = elem.StartDataTime?.Month <= 9 ? $"0{elem.StartDataTime?.Month}" : $"{elem.StartDataTime?.Month}";
                string sdtd = elem.StartDataTime?.Day <= 9 ? $"0{elem.StartDataTime?.Day}" : $"{elem.StartDataTime?.Day}";
                string sdth = elem.StartDataTime?.Hour <= 9 ? $"0{elem.StartDataTime?.Hour}" : $"{elem.StartDataTime?.Hour}";
                string sdtmin = elem.StartDataTime?.Minute <= 9 ? $"0{elem.StartDataTime?.Minute}" : $"{elem.StartDataTime?.Minute}";


                string edtm = elem.EndDataTime?.Month <= 9 ? $"0{elem.EndDataTime?.Month}" : $"{elem.EndDataTime?.Month}";
                string edtd = elem.EndDataTime?.Day <= 9 ? $"0{elem.EndDataTime?.Day}" : $"{elem.EndDataTime?.Day}";
                string edth = elem.EndDataTime?.Hour <= 9 ? $"0{elem.EndDataTime?.Hour}" : $"{elem.EndDataTime?.Hour}";
                string edtmin = elem.EndDataTime?.Minute <= 9 ? $"0{elem.EndDataTime?.Minute}" : $"{elem.EndDataTime?.Minute}";

                model.appointments.Add(new AppointmentForCalendarDTO
                {
                    id = elem.Id.ToString(),
                    title = "Busy",
                    description = "",
                    //title = $"{elem.AuthorizedUser.FirstName} {elem.AuthorizedUser.LastName}",
                    //description = elem.AdditionalInfo,
                    start = $"{elem.StartDataTime?.Year}-{sdtm}-{sdtd}T{sdth}:{sdtmin}:00",
                    end = $"{elem.EndDataTime?.Year}-{edtm}-{edtd}T{edth}:{edtmin}:00"
                });
            }

            model.json = JsonConvert.SerializeObject(model.appointments);
            return PartialView(model);
        }

        [HttpGet]
        public async Task<IActionResult> CreateAppointment(int id)
        {
            var userId = await GetCurrentUserId();
            CreateAppointmentDTO createAppointmentDTO = new CreateAppointmentDTO();

            createAppointmentDTO.CurrentPsychologist = _unitOfWork.Psychologists.Get(id);

            createAppointmentDTO.CurrentAuthorizedUser = _unitOfWork.AuthorizedUsers.Get(userId);

            createAppointmentDTO.Psychologists = new List<Psychologist>();//_unitOfWork.Psychologists.GetAll().ToList();
            createAppointmentDTO.AuthorizedUsers = new List<AuthorizedUser>();//_unitOfWork.AuthorizedUsers.GetAll().ToList();

            return PartialView(createAppointmentDTO);
        }

        [HttpPost]
        public IActionResult CreateAppointment(CreateAppointmentDTO model)
        {
            string _status = String.Empty;
            string _description = String.Empty;

            List<Appointment> appointments = _unitOfWork.Psychologists.Get(model.PsychologistId).Appointments.ToList();

            string currDayOfWeek = DateTime.Now.DayOfWeek.ToString();
            Day day = (Day)Enum.Parse(typeof(Day), currDayOfWeek);
            //var kek = model.CurrentPsychologist.WorkSchedules.Where(s => s.Day == day).FirstOrDefault();
            var kek = _unitOfWork.Psychologists.Get(model.PsychologistId).WorkSchedules.Where(s => s.Day == day).FirstOrDefault();


            foreach (var elem in appointments)
            {
                if ((model.StartDateTime >= elem.StartDataTime && model.StartDateTime <= elem.EndDataTime) ||
                    (model.EndDateTime >= elem.StartDataTime && model.EndDateTime <= elem.EndDataTime) ||
                    (elem.StartDataTime >= model.StartDateTime && elem.EndDataTime <= model.EndDateTime))
                {
                    _status = "error";
                    _description = "Doctor is busy at that time.";

                    break;
                }
            }

            if (_status != "error")
            {
                if (!(model.StartDateTime?.Hour >= kek?.StartTime.Hours &&
                        model.StartDateTime?.Minute >= kek?.StartTime.Minutes &&
                        model.EndDateTime?.Hour < kek?.EndTime.Hours))
                {
                    _status = "error";
                    _description = "Doctor does not work at this time.";
                }
            }

            if (_status != "error")
            {
                Appointment appointment = new Appointment
                {
                    PsychologistId = model.PsychologistId,
                    AuthorizedUserId = model.AuthorizedUserId,
                    StartDataTime = model.StartDateTime,
                    EndDataTime = model.EndDateTime,
                    AdditionalInfo = model.Info,
                    Finished = false
                };

                _unitOfWork.Appointments.Add(appointment);
                int result = _unitOfWork.Complete();

                _status = "success";
                _description = "Appointment created.";
            }
            //if (User.IsInRole("Doctor"))
            {
                //return RedirectToAction("DashboardDoctor", "User", new { showAll = false });
            }
            //else
            {
                //return RedirectToAction("DashboardPatient", "User", new { showAll = false });
            }

            return Json(new { status = _status, description = _description });
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Reports(int id)
        {
            var psychologist = _unitOfWork.Psychologists.Get(id);
            ReportsDTO reportsDTO = new ReportsDTO();
            reportsDTO.Psychologist = psychologist;

            var reportsFromDB = _unitOfWork.Reports.GetAll().Where(r => r.PsychologistId == id && r.IsVisible == true).OrderByDescending(r => r.Id).ToList();
            List<ReportDTO> reportDTOs = new List<ReportDTO>();
            /*for (int i = 0; i < reportsFromDB.Count; i++)
            {
                if(reportsFromDB[i].IsAnonymous)
                {
                    reportsFromDB[i].AuthorizedUser.FirstName = "Suka" + i;
                    reportsFromDB[i].AuthorizedUser.LastName = "";
                }
            }
            reportsDTO.Reports = reportsFromDB;*/
            foreach(var elem in reportsFromDB)
            {
                reportDTOs.Add(new ReportDTO
                {
                    Message = elem.Message,
                    IsAnonymous = elem.IsAnonymous,
                    FirstName = elem.IsAnonymous ? "Anonymous" : elem.AuthorizedUser.FirstName,
                    LastName = elem.IsAnonymous ? "" : elem.AuthorizedUser.LastName
                });
            }

            reportsDTO.Reports = reportDTOs;

            return PartialView(reportsDTO);
        }

        [HttpGet]
        public IActionResult AddReport(int id)
        {
            CreateReportDTO createReportDTO = new CreateReportDTO();

            var psychologist = _unitOfWork.Psychologists.Get(id);
            var authorizedUser = GetCurrentUserAsync().Result;

            createReportDTO.PsychologistId = id;
            createReportDTO.PsychologistName = $"{psychologist.FirstName} {psychologist.LastName}";
            createReportDTO.AuthorizedUserId = authorizedUser.Id;
            createReportDTO.AuthorizedUserName = $"{authorizedUser.FirstName} {authorizedUser.LastName}";
            createReportDTO.IsChecked = false;

            return View(createReportDTO);
        }

        [HttpPost]
        public IActionResult AddReport(CreateReportDTO model)
        {
            string _status = String.Empty;
            string _description = String.Empty;

            Report report = new Report()
            {
                Message = model.Message,
                PsychologistId = model.PsychologistId,
                AuthorizedUserId = model.AuthorizedUserId,
                IsAnonymous = model.IsChecked

Psycho.io/Views/Psychologist/AddReport.cshtml
@model Psycho.DTO.Core.CreateReportDTO
@{
    ViewBag.Title = "Add report";
    var content = ((HospitalContent)ViewData["lang"])?.Doctors?.AddReport;
}

<style>
    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
    }
</style>

<div class="container" style="margin-top: 150px;">
    <form asp-controller="Psychologist" asp-action="AddReport"
            data-ajax="true"
            data-ajax-method="POST"
            data-ajax-mode="replace"
            data-ajax-update=""
            data-ajax-success="SuccessAddedReport">

        <input type="number" asp-for="PsychologistId" hidden />
        <input type="number" asp-for="AuthorizedUserId" hidden />
        <div class="col-md-12 mb-4" style="">
            <!--Content-->
            <div class="modal-content form-elegant">
                <!--Header-->
                <div class="modal-header text-center">
                    <h3 class="modal-title w-100 dark-grey-text font-weight-bold my-3" id="myModalLabel"><strong>@(content?.AddReportFor ?? "Add report for") @Model.PsychologistName</strong></h3>
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>*@
                </div>
                <div class="modal-body mx-4">
                    <div class="row">

                        <!-- Grid column -->
                        <div class="col">

                            <div class="media">
                                <img class="d-flex mr-3" src="~/img/user.png" alt="Profile avatar" width="64">
                                <div class="media-body">
                                    <h5 class="mt-0 font-weight-bold">@Model.AuthorizedUserName</h5>
                                    <div class="md-form mb-5">
                                        <textarea type="text" id="reportMessage" class="form-control validate md-textarea" asp-for="Message" rows="3"></textarea>
                                        <label data-error="wrong" data-success="right" for="reportMessage" asp-for="Message">@(content?.YourReport ?? "Your report")</label>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-3">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="materialLoginFormRemember" asp-for="IsChecked">
                                    <label class="form-check-label" for="materialLoginFormRemember" asp-for="IsChecked">@(content?.Anonymous ?? "Anonymous")</label>
                                </div>
                            </div>

                        </div>

                    </div>

                    <hr />

                    <div class="row">

                        <!-- Grid column -->
                        <div class="col-md-12">


                            <div class="text-center mb-3">
                                <button id="submitBtn" type="submit" class="btn blue-gradient btn-block btn-rounded z-depth-1a">@(content?.AddBtn ?? "Add")</button>
                            </div>

                        </div>
                        <!-- Grid column -->

                    </div>

                </div>
            </div>
            <!--/.Content-->
        </div>
    </form>
</div>

<footer class="page-footer text-center text-md-left stylish-color-dark pt-0">
    <!-- Copyright-->
    <div class="footer-copyright py-3 text-center wow fadeIn" data-wow-delay="0.3s">
        <div class="container-fluid">
            © 2019 Copyright: <a href="#" target="_blank"> VL </a>
        </div>
    </div>
    <!--/.Copyright -->
</footer>

<script>
    function SuccessAddedReport(data) {
        toastr.success(data.description);
        $('#reportMessage').prop('disabled', true);
        $('input').prop('disabled', true);
        $('#submitBtn').prop('disabled', true);
    }
</script>

@section scripts {

}

Psycho.io/Views/Psychologist/CreateAppointment.cshtml
@model Psycho.DTO.Core.CreateAppointmentDTO
@{
    var content = ((HospitalContent)ViewData["lang"])?.Doctors?.CreateAppointment;
}

<form asp-controller="Psychologist" asp-action="CreateAppointment"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="replace"
      data-ajax-update=""
      data-ajax-success="SuccessSign">
    <div class="col-md-12 mb-4" style="">
        <!--Content-->
        <div class="modal-content form-elegant">
            <!--Header-->
            <div class="modal-header text-center">
                <h3 class="modal-title w-100 dark-grey-text font-weight-bold my-3" id="myModalLabel"><strong>@(content?.PageTitle ?? "Create appointment")</strong></h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-4">
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-6">

                        <div class="md-form form-sm mb-0">
                            <select class="browser-default custom-select custom-select-md" asp-for="PsychologistId" required>
                                    <option selected value="@Model.CurrentPsychologist.Id">@{
                                        string name = $"{Model.CurrentPsychologist.FirstName} {Model.CurrentPsychologist.LastName}";
                                    }
                                    @name</option>
                            </select>
                        </div>

                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-lg-6">

                        <div class="md-form form-sm mb-0">
                            <select class="browser-default custom-select custom-select-md" asp-for="AuthorizedUserId" required>
                                    <option selected value="@Model.CurrentAuthorizedUser.Id">@{
                                        string userName = $"{Model.CurrentAuthorizedUser.FirstName} {Model.CurrentAuthorizedUser.LastName}";
                                    }
                                    @userName</option>

                            </select>
                        </div>

                    </div>
                    <!-- Grid column -->

                </div>


                <div class="row">

                    <!-- Grid column -->
                    <div class="col-md-6">

                        <!--<div class="md-form form-sm mb-0" id="sPicker">
                            <input type="text" id="startPicker" class="form-control form-control-sm" asp-for="StartDateTime" required>
                            <label for="startPicker" class="" asp-for="StartDateTime">Start Time</label>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>-->

                        <div class="form-group" style="margin-top: 1.5rem;">
                            <div class="input-group date" id="sPicker" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" data-target="#sPicker" asp-for="StartDateTime" required/>
                                <div class="input-group-append" data-target="#sPicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-6">

                        <div class="form-group" style="margin-top: 1.5rem;">
                            <div class="input-group date" id="ePicker" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" data-target="#ePicker" asp-for="EndDateTime" required/>
                                <div class="input-group-append" data-target="#ePicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row -->

                <div class="row">

                    <!-- Grid column -->
                    <div class="col-md-12">
                    
                        <!-- Basic textarea -->
                        <div class="md-form mb-0">
                            <textarea type="text" id="app_info" class="md-textarea form-control" rows="2" asp-for="Info"></textarea>
                            <label for="app_info">@(content?.AdditionalInfo ?? "Additional info")</label>
                        </div>

                    </div>
                    <!-- Grid column -->

                </div>

                <hr />

                <div class="row">

                    <!-- Grid column -->
                    <div class="col-md-12">


                        <div class="text-center mb-3">
                            <button type="submit" class="btn blue-gradient btn-block btn-rounded z-depth-1a">@(content?.CreateBtn ?? "Create")</button>
                        </div>

                    </div>
                    <!-- Grid column -->

                </div>

            </div>
        </div>
        <!--/.Content-->
    </div>
</form>

@section scripts {

}

Psycho.io/Views/Psychologist/Index.cshtml
@{
    ViewData["Title"] = "Doctors";
    var content = ((HospitalContent)ViewData["lang"])?.Doctors?.Index;
}

@using Psycho.io.Models.Doctor
@model DoctorsViewModel

@section csss {
    <link href="~/css/admin/datatables.min.css" rel="stylesheet">
    <link href="~/css/page.css" rel="stylesheet">
    <link href="~/css/psychologists-page.css" rel="stylesheet">
}


<div class="modal fade" id="darkModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="dialogContentUp" class="modal-dialog" role="document"></div>
</div>
<div class="modal fade" id="modalFormSchedulePsychologist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="dialogContentSchedulePsychologist" class="modal-dialog" role="document"></div>
</div>
<div class="modal fade" id="modalFormSignPsychologist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="dialogContentSignPsychologist" class="modal-dialog" role="document"></div>
</div>
<div class="modal fade" id="modalFormViewAllPsychologist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="dialogContentViewAllPsychologist" class="modal-dialog" role="document"></div>
</div>
<div class="modal fade" id="modalFormAddReport" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div id="dialogContentAddReport" class="modal-dialog" role="document"></div>
</div>

<main style="min-height: 100vh;">
    <div class="container-fluid mb-5">

        <section>
            <div class="col-md-12">

                <div class="d-flex justify-content-between">
                    <h5 class="my-4 dark-grey-text font-weight-bold">@(content?.PageTitle ?? "Doctors")</h5>
                </div>

                <div class="card">
                    <div class="card-body">
                        <table id="dtMaterialDesignExample" class="table table-striped" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    @foreach (var header in content?.GeneralColumnHeaders ?? Model.Doctors.GeneralColumnHeaders)
                                    {
                                        <th>@header</th>
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var psychologist in Model.Doctors.PsychologistDTOs)
                                {
                                    <tr>
                                        <td>
                                            <img src="../img/man.png" class="rounded-circle" alt="Avatar image" width="100">
                                        </td>
                                        @{
                                            System.Collections.Generic.List<string> list = psychologist.ToGeneralList();
                                        }
                                        @foreach (var elem in list)
                                        {
                                            <td>@elem</td>
                                        }

                                        <td>
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col align-self-center">
                                                        @Html.ActionLink(content?.ScheduleBtn ?? "Schedule", "Schedule", "Psychologist", new { id = psychologist.Id }, new
                                                        {
                                                            data_ajax = "true",
                                                            data_ajax_method = "GET",
                                                            data_ajax_mode = "replace",
                                                            data_ajax_update = "",
                                                            data_ajax_success = "ScheduleButtonSuccess",
                                                            @class = "btn btn-outline-default btn-rounded waves-effect",
                                                            @id = "edit-psychologist"
                                                        })
                                                    </div>
                                                </div>
                                                @if (User.IsInRole("AuthorizedUser"))
                                                {
                                                    <div class="row" style="padding-top: 7px">
                                                        <div class="col align-self-center">
                                                            @Html.ActionLink(content?.SignBtn ?? "Sign", "CreateAppointment", "Psychologist", new { id = psychologist.Id }, new
                                                            {
                                                                data_ajax = "true",
                                                                data_ajax_method = "GET",
                                                                data_ajax_mode = "replace",
                                                                data_ajax_update = "",
                                                                data_ajax_success = "SignButtonSuccess",
                                                                @class = "btn btn-outline-secondary btn-rounded waves-effect"
                                                            })
                                                        </div>
                                                    </div>
                                                }
                                                @if (User.IsInRole("AuthorizedUser") || User.IsInRole("AnonymousUser"))
                                                {
                                                    <a asp-controller="User" asp-action="Chat" asp-route-friendId="@psychologist.Id" class="btn btn-outline-info btn-rounded waves-effect" style="margin-top: 7px">@(content?.ChatBtn ?? "Chat")</a>
                                                }

                                            </div>
                                        </td>

                                        <td>
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col align-self-center">
                                                        @Html.ActionLink(content?.ViewAllReportsBtn ?? "View all", "Reports", "Psychologist", new { id = psychologist.Id }, new
                                                        {
                                                            data_ajax = "true",
                                                            data_ajax_method = "GET",
                                                            data_ajax_mode = "replace",
                                                            data_ajax_update = "editUserInfo",
                                                            data_ajax_success = "ViewAllButtonSuccess",
                                                            @class = "btn btn-outline-primary btn-rounded waves-effect"
                                                        })
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    @if (false/*User.IsInRole("AuthorizedUser")*/)
                                                    {
                                                        <div class="col align-self-center" style="padding-top: 7px">
                                                            @Html.ActionLink(content?.AddReportBtn ?? "Add", "AddReport", "Psychologist", new { id = psychologist.Id }, new
                                                            {
                                                                data_ajax = "true",
                                                                data_ajax_method = "GET",
                                                                data_ajax_mode = "replace",
                                                                data_ajax_update = "deleteUserInfo",
                                                                data_ajax_success = "AddReportButtonSuccess",
                                                                @class = "btn btn-outline-danger btn-rounded waves-effect"
                                                            })
                                                        </div>
                                                    }

                                                </div>
                                            </div>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                            
                        </table>

                        <nav aria-label="Doctors navigation">
                            @{
                                var disableNext = Model.NumberOfPages == 1 ? "disabled" : "";
                            }
                            <ul class="pagination pg-blue justify-content-center">
                                <li class="page-item disabled">
                                    <a class="page-link" link-value="prev">@(content?.PreviousBtn ?? "Previous")</a>
                                </li>
                                <li class="page-item active"><a class="page-link" link-value="1">1</a></li>
                                @for (var i = 0; i < Model.NumberOfPages - 1; i++)
                                {
                                    var val = i + 2;
                                    <li class="page-item"><a class="page-link" link-value="@val">@val</a></li>
                                }
                                <li class="page-item @disableNext">
                                    <a class="page-link" link-value="next">@(content?.NextBtn ?? "Next")</a>
                                </li>
                            </ul>
                        </nav>

                    </div>
                </div>

            </div>
        </section>
    </div>
</main>

<footer class="page-footer text-center text-md-left stylish-color-dark pt-0">
    <!-- Copyright-->
    <div class="footer-copyright py-3 text-center wow fadeIn" data-wow-delay="0.3s">
        <div class="container-fluid">
            © 2019 Copyright: <a href="#" target="_blank"> VL </a>
        </div>
    </div>
    <!--/.Copyright -->
</footer>

@section scripts {
    <script type="text/javascript" src="~/js/psychologists-page.js"></script>
}